version: '3.3'

services:
  postgres-docker:
    image: "postgres:11"
    restart: always
    container_name: "postgres-spring-skeleton"
    environment:
      POSTGRES_DB: spring-skeleton
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres-docker-data:/var/lib/postgresql/data

  spring-skeleton-app:
    image: spring-skeleton-image
    ports:
      - 8080:8080
    expose:
      - '8080'
    depends_on:
      - postgres-docker
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/spring-boot-app

volumes:
  postgres-docker-data:
