spring:
  application:
    name: spring-skeleton
  datasource:
    url: jdbc:postgresql://postgres-docker:5432/spring-skeleton
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8080
  servlet:
    context-path: /spring-skeleton

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full

via-cep:
  client:
    url: https://viacep.com.br/
